# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 38) do

  create_table "assets", :force => true do |t|
    t.column "type", :string
    t.column "content_type", :string
    t.column "filename", :string
    t.column "path", :string
  end

  create_table "assets_themes", :id => false, :force => true do |t|
    t.column "asset_id", :integer
    t.column "theme_id", :integer
  end

  create_table "attachments", :force => true do |t|
    t.column "content_type", :string
    t.column "filename", :string
    t.column "size", :integer
    t.column "parent_id", :integer
    t.column "thumbnail", :string
    t.column "width", :integer
    t.column "height", :integer
    t.column "type", :string
    t.column "guide_id", :integer
    t.column "user_id", :integer
    t.column "theme_id", :integer
  end

  create_table "choices", :force => true do |t|
    t.column "name", :string
    t.column "description", :text
    t.column "selection", :string
    t.column "contest_id", :integer
    t.column "position", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "contests", :force => true do |t|
    t.column "name", :string
    t.column "description", :text
    t.column "type", :string
    t.column "guide_id", :integer
    t.column "position", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "endorsement_drafts", :force => true do |t|
    t.column "endorsement_id", :integer
    t.column "updated_at", :datetime
    t.column "guide_id", :integer
    t.column "contest", :string
    t.column "candidate", :string
    t.column "position_id", :integer
    t.column "description", :text
  end

  create_table "endorsements", :force => true do |t|
    t.column "guide_id", :integer
    t.column "contest", :string
    t.column "candidate", :string
    t.column "description", :text
    t.column "position", :integer
    t.column "selection", :string
  end

  create_table "guide_drafts", :force => true do |t|
    t.column "guide_id", :integer
    t.column "updated_at", :datetime
    t.column "name", :string
    t.column "city", :string
    t.column "state", :string
    t.column "date", :date
    t.column "description", :text
    t.column "owner_id", :integer
    t.column "theme_id", :integer
    t.column "endorsements", :text
  end

  create_table "guides", :force => true do |t|
    t.column "name", :string
    t.column "description", :text
    t.column "city", :string
    t.column "state", :string
    t.column "date", :date
    t.column "user_id", :integer
    t.column "theme_id", :integer
    t.column "permalink", :string
    t.column "status", :string
    t.column "endorsed", :boolean
    t.column "legal", :string
    t.column "approved_at", :datetime
    t.column "approved_by", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "links", :force => true do |t|
    t.column "url", :string
    t.column "description", :text
    t.column "guide_id", :integer
  end

  create_table "pledges", :force => true do |t|
    t.column "user_id", :integer
    t.column "guide_id", :integer
  end

  create_table "resources", :force => true do |t|
    t.column "content_type", :string
    t.column "filename", :string
    t.column "size", :integer
    t.column "parent_id", :integer
    t.column "thumbnail", :string
    t.column "width", :integer
    t.column "height", :integer
  end

  create_table "roles", :force => true do |t|
    t.column "title", :string
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer
    t.column "user_id", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data", :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "styles", :force => true do |t|
    t.column "stylesheet", :text
    t.column "author_id", :integer
    t.column "name", :string
  end

  create_table "themes", :force => true do |t|
    t.column "name", :string
    t.column "style_id", :integer
    t.column "author_id", :integer
    t.column "print_style_id", :integer
    t.column "style_url", :string
    t.column "print_style_url", :string
    t.column "template", :string
  end

  create_table "users", :force => true do |t|
    t.column "login", :string
    t.column "email", :string
    t.column "crypted_password", :string, :limit => 40
    t.column "salt", :string, :limit => 40
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "activation_code", :string, :limit => 40
    t.column "activated_at", :datetime
    t.column "password_reset_code", :string, :limit => 40
    t.column "street", :string
    t.column "city", :string
    t.column "state", :string
    t.column "postal_code", :string
    t.column "phone", :string
    t.column "signup_domain", :string
    t.column "firstname", :string
    t.column "lastname", :string
    t.column "url", :string
    t.column "about_me", :text
  end

end
