# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "endorsements", :force => true do |t|
    t.column "guide_id", :integer
    t.column "contest", :string
    t.column "candidate", :string
    t.column "position_id", :integer
    t.column "description", :text
  end

  create_table "guides", :force => true do |t|
    t.column "name", :string
    t.column "description", :text
    t.column "city", :string
    t.column "state", :string
    t.column "date", :date
    t.column "owner_id", :integer
  end

  create_table "positions", :force => true do |t|
    t.column "text", :string
  end

  create_table "users", :force => true do |t|
    t.column "login", :string
    t.column "email", :string
    t.column "crypted_password", :string, :limit => 40
    t.column "salt", :string, :limit => 40
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

end
